### ISSUE TITLE
react子项目都是报错，其中一个报'__webpack_public_path__' is not defined

### ISSUE THREAD

**Issue by Chasen-Zhang** [CHU295/Micro-Frontends-practice#18]
![image](https://user-images.githubusercontent.com/15354455/84900118-3f543b80-b0dc-11ea-9e47-5e1442a8354f.png)
![image](https://user-images.githubusercontent.com/15354455/84900138-467b4980-b0dc-11ea-8213-93220545977f.png)

**Comment by AHopes** [comment]
请问下解决了吗

**Comment by liuxuzxx** [comment]
运行了下react_也是报这个错误

**Comment by AHopes** [comment]
/* global __webpack_public_path__:writable */
可以试着加下这个，我的解决了，是eslint不允许访问变量

**Comment by liuxuzxx** [comment]
> /* global **webpack_public_path**:writable */
> 可以试着加下这个，我的解决了，是eslint不允许访问变量

这个是注释加到public-path.js文件当中？

**Comment by AHopes** [comment]
是的

**Comment by easy11** [comment]
还可以在public-path.js里面写一行注释 // eslint-disable-next-line no-undef 即可解决eslint的这个报错。public-path.js的完整代码如下
```
if (window.__POWERED_BY_QIANKUN__) {
  // eslint-disable-next-line no-undef
  __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__;
}
```
qiankun官方文档里有这段代码，不要随便改或者删掉那行注释，是有用的~
